chore(docs): Remove warning
Disploy/disploy pull request #77
Opened 2022-12-05 13:38 UTC by Nciklol

2022-12-05 13:42 UTC, twisttaan commented
You should also refactor https://github.com/Disploy/disploy/blob/560a2a99da17588f69362fe0ef87c62d0edae25a/apps/docs/docs/getting-started/cli-framework/prep-work/creating-a-new-project.md?plain=1#L9-L12 since `npx` is only supported now

2022-12-05 13:42 UTC, twisttaan requested changes
You should also refactor https://github.com/Disploy/disploy/blob/560a2a99da17588f69362fe0ef87c62d0edae25a/apps/docs/docs/getting-started/cli-framework/prep-work/creating-a-new-project.md?plain=1#L9-L12 since `npx` is only supported now

2022-12-05 15:41 UTC, Nciklol commented
Not sure what to do to make the command fit better, should I merge the 2 parts of the page into one?

2022-12-05 20:43 UTC, twisttaan commented on apps/docs/docs/getting-started/cli-framework/prep-work/creating-a-new-project.md
> +## Start by running the command:
Maybe “Bootstrap a new project” with a description explaining how CDA gets you started with a basic template.

2022-12-05 20:44 UTC, twisttaan requested changes
Address reviews

2022-12-14 12:28 UTC, twisttaan approved these changes

2022-12-14 12:29 UTC, GodderE2D commented
Why was yarn/npm create removed?

2022-12-14 12:29 UTC, twisttaan commented
It's not supported.

2022-12-14 12:30 UTC, GodderE2D commented
Is there any specific reason why?

2022-12-14 12:32 UTC, twisttaan commented
Actually never mind, it does seem to work now. I tested it during the development of CDA, turns out yarn was just caching and an older version was published which was broken.
![Screenshot 2022-12-14 at 11 32 31 pm](https://user-images.githubusercontent.com/69066026/207596154-a67907d1-180e-4c78-8ce6-d5e0ac68b65c.png)

2022-12-14 12:39 UTC, twisttaan commented
> Resolve ci issues (I have no idea how the ci works)

It's fine, the windows CLI tests always fail on pull requests because of some caching issue I need to investigate more. And the vercel preview failed because it's using a new configuration which isn't supported in the branch of this pull request because it needs to be updated w/ upstream.

2022-12-14 12:56 UTC, GodderE2D approved these changes

2022-12-14 12:58 UTC, merged